// <auto-generated />
namespace CinemaTicket.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class themtablecelebrityvarangbuocvoimovie : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(themtablecelebrityvarangbuocvoimovie));
        
        string IMigrationMetadata.Id
        {
            get { return "202303170855146_them table celebrity va rang buoc voi movie"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
