// <auto-generated />
namespace CinemaTicket.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Taolienket1nvoiCinemaShowdayShowTimeMovievsShow : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Taolienket1nvoiCinemaShowdayShowTimeMovievsShow));
        
        string IMigrationMetadata.Id
        {
            get { return "202303160257527_Tao lien ket 1 n voi CinemaShowdayShowTimeMovie vs Show"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
