// <auto-generated />
namespace CinemaTicket.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Taolienket1nvoiSeatvsreservation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Taolienket1nvoiSeatvsreservation));
        
        string IMigrationMetadata.Id
        {
            get { return "202303160232460_Tao lien ket 1 n voi Seat vs reservation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
